#!/bin/bash
#SBATCH --job-name=analyze_ase         # Job name
#SBATCH -o slurm.%j.out                # STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err                # STDERR (%j = JobId)

cd /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter

sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-Cont02_180_013_S184_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_CON02_VW-ASUPlace-Cont02_180_013_S184_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-Cont02_180_013_S184_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_CON02_VW-ASUPlace-Cont02_180_013_S184_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-Cont03_168_025_S185_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_CON03_VW-ASUPlace-Cont03_168_025_S185_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-Cont03_168_025_S185_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_CON03_VW-ASUPlace-Cont03_168_025_S185_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-Cont05-Q1RNA1_144_049_S187_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_CON05_VW-ASUPlace-Cont05-Q1RNA1_144_049_S187_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-Cont05-Q1RNA1_144_049_S187_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_CON05_VW-ASUPlace-Cont05-Q1RNA1_144_049_S187_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-Cont06-Q1RNA1_132_061_S188_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_CON06_VW-ASUPlace-Cont06-Q1RNA1_132_061_S188_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-Cont06-Q1RNA1_132_061_S188_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_CON06_VW-ASUPlace-Cont06-Q1RNA1_132_061_S188_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-Cont10-Q1RNA1_179_014_S192_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_CON10_VW-ASUPlace-Cont10-Q1RNA1_179_014_S192_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-Cont10-Q1RNA1_179_014_S192_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_CON10_VW-ASUPlace-Cont10-Q1RNA1_179_014_S192_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-HDP01_167_026_S193_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_HDP01_VW-ASUPlace-HDP01_167_026_S193_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-HDP01_167_026_S193_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_HDP01_VW-ASUPlace-HDP01_167_026_S193_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-HDP08-Q1RNA1_178_015_S200_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_HDP08_VW-ASUPlace-HDP08-Q1RNA1_178_015_S200_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-HDP08-Q1RNA1_178_015_S200_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_HDP08_VW-ASUPlace-HDP08-Q1RNA1_178_015_S200_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-HDP09-Q1RNA1_166_027_S201_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_HDP09_VW-ASUPlace-HDP09-Q1RNA1_166_027_S201_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-HDP09-Q1RNA1_166_027_S201_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_HDP09_VW-ASUPlace-HDP09-Q1RNA1_166_027_S201_L001_chrX_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chr8/VW-ASUPlace-HDP10-Q1RNA1_154_039_S202_L001_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chr8/Plac_HDP10_VW-ASUPlace-HDP10-Q1RNA1_154_039_S202_L001_chr8_allele_balance.tsv"
sbatch --mem=20G -n 2 --wrap="python /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/scripts/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/HISAT/Q1/chrX/VW-ASUPlace-HDP10-Q1RNA1_154_039_S202_L001_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/asereadcounter/analyze_ase_results/allele_balance_tables/Q1/chrX/Plac_HDP10_VW-ASUPlace-HDP10-Q1RNA1_154_039_S202_L001_chrX_allele_balance.tsv"
