mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_CON01_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON01_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_CON01_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON01_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_CON01_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON01_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_CON01_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON01_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_CON01_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON01_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_CON01_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON01_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_CON01_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON01_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_CON01_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON01_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_CON04_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON04_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_CON04_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON04_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_CON04_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON04_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_CON04_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON04_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_CON04_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON04_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_CON04_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON04_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_CON04_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON04_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_CON04_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON04_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_CON07_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON07_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_CON07_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON07_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_CON07_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON07_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_CON07_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON07_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_CON07_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON07_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_CON07_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON07_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_CON07_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON07_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_CON07_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON07_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_CON08_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON08_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_CON08_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON08_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_CON08_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON08_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_CON08_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON08_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_CON08_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON08_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_CON08_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON08_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_CON08_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON08_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_CON08_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON08_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_CON09_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON09_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_CON09_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON09_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_CON09_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON09_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_CON09_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON09_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_CON09_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON09_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_CON09_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON09_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_CON09_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON09_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_CON09_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON09_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP01_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP01_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP01_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP01_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP01_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP01_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP01_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP01_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP01_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP01_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP01_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP01_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP01_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP01_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP01_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP01_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP03_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP03_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP03_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP03_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP03_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP03_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP03_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP03_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP03_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP03_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP03_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP03_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP03_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP03_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP03_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP03_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP04_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP04_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP04_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP04_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP04_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP04_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP04_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP04_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP04_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP04_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP04_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP04_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP04_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP04_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP04_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP04_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP06_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP06_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP06_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP06_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP06_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP06_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP06_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP06_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP06_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP06_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP06_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP06_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP06_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP06_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP06_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP06_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP07_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP07_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP07_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP07_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP07_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP07_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP07_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP07_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP07_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP07_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP07_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP07_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP07_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP07_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP07_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP07_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chr8/Plac_HDP05_Q1_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP05_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q1/chrX/Plac_HDP05_Q1_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP05_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chr8/Plac_HDP05_Q2_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP05_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q2/chrX/Plac_HDP05_Q2_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP05_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chr8/Plac_HDP05_Q3_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP05_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q3/chrX/Plac_HDP05_Q3_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP05_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chr8/Plac_HDP05_Q4_chr8_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP05_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/HISAT/Q4/chrX/Plac_HDP05_Q4_chrX_males.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/05_males/males_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP05_Q4_chrX_allele_balance.tsv"
