mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_CON02_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON02_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_CON02_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON02_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_CON02_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON02_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_CON02_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON02_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_CON02_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON02_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_CON02_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON02_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_CON02_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON02_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_CON02_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON02_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_CON03_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON03_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_CON03_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON03_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_CON03_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON03_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_CON03_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON03_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_CON03_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON03_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_CON03_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON03_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_CON03_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON03_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_CON03_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON03_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_CON06_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON06_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_CON06_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON06_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_CON06_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON06_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_CON06_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON06_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_CON06_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON06_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_CON06_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON06_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_CON06_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON06_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_CON06_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON06_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_CON05_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON05_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_CON05_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON05_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_CON05_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON05_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_CON05_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON05_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_CON05_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON05_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_CON05_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON05_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_CON05_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON05_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_CON05_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON05_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_CON10_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_CON10_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_CON10_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_CON10_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_CON10_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_CON10_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_CON10_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_CON10_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_CON10_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_CON10_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_CON10_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_CON10_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_CON10_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_CON10_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_CON10_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_CON10_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_HDP02_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP02_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_HDP02_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP02_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_HDP02_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP02_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_HDP02_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP02_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_HDP02_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP02_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_HDP02_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP02_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_HDP02_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP02_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_HDP02_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP02_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_HDP08_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP08_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_HDP08_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP08_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_HDP08_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP08_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_HDP08_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP08_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_HDP08_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP08_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_HDP08_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP08_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_HDP08_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP08_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_HDP08_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP08_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_HDP09_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP09_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_HDP09_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP09_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_HDP09_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP09_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_HDP09_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP09_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_HDP09_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP09_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_HDP09_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP09_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_HDP09_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP09_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_HDP09_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP09_Q4_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chr8/Plac_HDP10_Q1_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chr8/Plac_HDP10_Q1_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q1/chrX/Plac_HDP10_Q1_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q1/chrX/Plac_HDP10_Q1_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chr8/Plac_HDP10_Q2_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chr8/Plac_HDP10_Q2_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q2/chrX/Plac_HDP10_Q2_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q2/chrX/Plac_HDP10_Q2_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chr8/Plac_HDP10_Q3_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chr8/Plac_HDP10_Q3_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q3/chrX/Plac_HDP10_Q3_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q3/chrX/Plac_HDP10_Q3_chrX_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chr8/Plac_HDP10_Q4_chr8_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chr8/Plac_HDP10_Q4_chr8_allele_balance.tsv"
mkdir -p /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/
sbatch --mem=20G -n 2 --wrap="python3 /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/calc_allele_balance.py --input /data/Wilson_Lab/projects/placentas_VW_ASE/02_run_asereadcounter/run_asereadcounter_correct_swapping/HISAT/Q4/chrX/Plac_HDP10_Q4_chrX_females.tsv --output /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/analyze_ase_correct_swapping/allele_balance_tables/Q4/chrX/Plac_HDP10_Q4_chrX_allele_balance.tsv"
