#!/bin/bash

python calc_median_allele_balance.py  --chromosome 8 --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q1/chr8 --threshold 10 --include_pars Yes --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chr8_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome 8 --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q2/chr8 --threshold 10 --include_pars Yes --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chr8_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome 8 --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q3/chr8 --threshold 10 --include_pars Yes --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chr8_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome 8 --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q4/chr8 --threshold 10 --include_pars Yes --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chr8_median_allele_balance.tsv

python calc_median_allele_balance.py  --chromosome X --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q1/chrX --threshold 10 --include_pars No --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chrX_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome X --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q2/chrX --threshold 10 --include_pars No --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chrX_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome X --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q3/chrX --threshold 10 --include_pars No --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chrX_median_allele_balance.tsv
python calc_median_allele_balance.py  --chromosome X --files_dir /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/allele_balance_tables/Q4/chrX --threshold 10 --include_pars No --out_placenta /data/Wilson_Lab/projects/placentas_VW_ASE/03_analyze_ase/median_allele_balance/chrX_median_allele_balance.tsv